# @package _global_

model:
  pretrained: False
  path: /iris/u/clin/code/editable_nlp/src/outputs/2021-06-08_19-49-26_0/models/finetune_epoch199_ts9999.2021-06-08_19-49-26_0
  # /iris/u/clin/code/editable_nlp/src/outputs/2021-06-02/10-36-49/models/finetune_epoch199_ts9999.2021-06-02.10-36-49
