debug: False
verbose: False
model_save_pt: 1000
silent: False
n_edits: 1
cbase: 1
lr_grad_clip: null
weight_decay: null
ortho: False
adapt_all: False

model:
  layernorm: False

bs: 128
edit_bs: 16
n_edit_steps: 5

defaults:
  - experiment: base_cifar_resnet
  - model: resnet18
