debug: False
model_save_pt: 1000
silent: False

loss: cross_entropy
model:
  layernorm: False

defaults:
  - alg: finetune
  - dataset: cifar10
  - model: resnet18
  - dataset_model: ${defaults.1.dataset}_${defaults.2.model}
    optional: True
  - alg_dataset_model: ${defaults.0.alg}_${defaults.1.dataset}_${defaults.2.model}
    optional: True

hydra:
  job:
    id: 0
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.id}
